### ISSUE TITLE
Any way to close issues based on project (v2) board column/status?

### ISSUE THREAD

**Issue by mnbf9rca** [peter-evans/close-issue#614]
We're using the new V2 projects. I'd like to close items when they enter the 'Done' column. I can filter them in the view using `status:Done` but do you know how i can retrieve the board column from the `github.event.issue` object within the workflow so i can filter it in the `if` condition?

**Comment by peter-evans** [comment]
Hi @mnbf9rca 

Sorry I don't know, but you should be able to figure this out by dumping the `github` context in a workflow step and finding the property you need for the condition.

```yml
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
```
